"""add sku and brand to products

Revision ID: 90a8b40f80e2
Revises: e2f9e590b4a9
Create Date: 2026-06-29 15:53:33.032966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90a8b40f80e2'
down_revision: Union[str, Sequence[str], None] = 'e2f9e590b4a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add brand column
    op.add_column(
        "products",
        sa.Column("brand", sa.String(length=100), nullable=True),
    )

    # 2. Add sku as nullable first
    op.add_column(
        "products",
        sa.Column("sku", sa.String(length=100), nullable=True),
    )

    # 3. Give every existing product a SKU
    op.execute(
        "UPDATE products SET sku = 'SKU-' || id WHERE sku IS NULL"
    )

    # 4. Make sku NOT NULL
    op.alter_column(
        "products",
        "sku",
        nullable=False,
    )

    # 5. Create indexes
    op.create_index(
        op.f("ix_products_brand"),
        "products",
        ["brand"],
        unique=False,
    )

    op.create_index(
        op.f("ix_products_sku"),
        "products",
        ["sku"],
        unique=True,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_brand'), table_name='products')
    op.drop_column('products', 'sku')
    op.drop_column('products', 'brand')
    # ### end Alembic commands ###
