"""update cart item model

Revision ID: e2f9e590b4a9
Revises: 66f927270236
Create Date: 2026-06-29 14:54:22.109076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2f9e590b4a9'
down_revision: Union[str, Sequence[str], None] = '66f927270236'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('cart_items', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_unique_constraint('uq_cart_user_product', 'cart_items', ['user_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_cart_user_product', 'cart_items', type_='unique')
    op.drop_column('cart_items', 'updated_at')
    op.drop_column('cart_items', 'created_at')
    # ### end Alembic commands ###
