"""add tags to products

Revision ID: fd1f225dfc95
Revises: 5ce3d0a9894e
Create Date: 2026-07-22 16:04:34.844127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd1f225dfc95'
down_revision: Union[str, Sequence[str], None] = '5ce3d0a9894e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('tags', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'tags')
    # ### end Alembic commands ###
